### PR TITLE
Includes test for greenboxing

### PR DESCRIPTION
**Pull request by thiagoarrais**
Partial fix for #30 

Is this going in the right direction? Does it need any more work? Just let me know!

### CODE REVIEW

**Comment by victorperin** [comment]
Hello @thiagoarrais thanks for your contribution. :)

Somethings i think must be changed:
- the test name seems to not to match with what happens in the test itself.
- i think we can add some other kind of tests there, like:
  - what's expected when we pass values like: null, undefined, -1, empty string, etc...

Somethings I personally like (feel free to disagree):
- I like unit testing to be on same folder as the original file (we can just ignore them on .npmignore, to production)
- I does feel safe with snapshot testing. There are some problems I had with it (most caused with the lack of code review) and also the fact it put what is expected on another file.

**Comment by thiagoarrais** [comment]
Agreed on the name change.

About keeping test files in the same src folder as original, I just thought the de facto pratice in npm-land was to have every test inside a separate `tests` folder. But, hey, it's your project man. I'll fix that as soon as I find some time.

**Comment by victorperin** [comment]
Thanks for that response, I agree on tests being inside of tests folder on npm packages is a trend.

I think this is an open debate about code architecture I really like, there are really good points in each case, like clear logic separation (all tests in /tests) or simple to find related tests (in the other).

I like and already implemented both solution, but my main focus on this issue is to separate integration tests from unit tests, right now. This is why I'm prefering to use the second aproach (unit tests in the same folder of the source).

Also, I think /tests files in NPM world was due to some limitations of the early days, that led to that state. Today we only need to add to .npmignore file a `*.test.js`

**Comment by victorperin** [comment]
Also, about the snapshot. what do you think? This is more important to me than the test path. :)

**Comment by thiagoarrais** [comment]
I've moved the tests next to the source. Let me know whether this looks good to you.

On the snapshot testing front, it sure seems weird at first having the expected output on a separate file, but you get used to it. Some other projects I collaborate on also use some flavours of snapshot testing and I'm already used to it.

About adding other tests, I think we can use this PR for defining structure and have them added in subsequent PRs.

**Comment by victorperin** [comment]
Snapshot testing, in my experience tends you towards updating the snapshot if it fail. Since it's just one command, people who does not have experience can do it without knowing what will it cause.

I recommend snapshot testing on places where the code get a lot of updates day to day and also generates a lot of context. (like a front-end component with some degree of complexity or something like that)

This can be changed to fit inside the same file (and also helps if get any problem, you can see it inside the file, without need to open other files).

I'll do a commit in your PR to fix it. :)

Also, thanks for the discussion and the PR. Things like this add quality to the project.

**Comment by victorperin** [comment]
I've accidentally discovered a problem:
when you run the test in a no-color tty, boxen dosn't output those characters, so, the tests fail.

We might need to change the way we are testing this.

**Comment by victorperin** [comment]
@thiagoarrais i've changed the approach to test the lib by mocking the boxen lib. This is the correct way to do unit tests, so I don't need to relay on the library complexity.

**Pull request merged**
