### PR TITLE
feat: add tests

### PR DESCRIPTION
**Pull request by lnfnunes**
Solves #2 

- [x] add jest
- [x] add happy path test
- [x] add bad path test: file not found
- [x] add other obscure bad path tests

### CODE REVIEW

**Comment by victorperin** [comment]
@lnfnunes i've made a huge refactor on the code. I didn't view your PR. can you look on your tests and check if they still make sense?

Again... sorry... hehe

**Comment by victorperin** [comment]
Thanks for the `execa` i was looking for something like this. :)

**Comment by victorperin** [comment]
I've made a rebase to do the merge and everything worked. I'm trying to push to your branch it right now.

**Comment by lnfnunes** [comment]
Niiice! @victorperin :D
ps: How do you push to my branch? I tried it once, one time ago, with no success rsrs

**Comment by victorperin** [comment]
@lnfnunes authors are by default authorized to push on branches other users created a pull request.
But i think an user can disable that.

Apart of it, you need to master a bit about remotes, because you need to add one for each user.

**Pull request merged**
