### PR TITLE
new gif added as demo

### PR DESCRIPTION
**Pull request by molly7657**

### CODE REVIEW

**Comment by molly7657** [comment]
Hi Victor - I took out other edits on the README and added gif as a file as suggested. Please let me know if you would like additional changes!

**Comment by molly7657** [comment]
Hi @victorperin, I made the text larger in the gif and connected the demo to the sample.jpg. Let me know if you need anything additionally. Thank you!

**Comment by victorperin** [comment]
Thanks @molly7657, it is perfect! :)
Merging right now.

**Comment by victorperin** [comment]
@molly7657 merged, thanks for your contribution! :)

**Pull request merged**
