### PR TITLE
refactor: add types (#62)

### PR DESCRIPTION
**Pull request by SimonSiefke**

### CODE REVIEW

**Comment by victorperin** [comment]
Hello there, @SimonSiefke. :)
Thanks for your contribution. Can you describe what exactly you have done in here?

I there is somethings i noticed:
- I don't like those `@ts-ignore` (never used ts inside js files, but they are in some way strange to me (what do you think, can we improve it?)
- You are also free to change .js files to .ts and add a build process, if necessary. I understand you kept it simple using .js files, but there's some problem for readability with this method.
- there are failing tests on every environment, please check them again.

**Comment by SimonSiefke** [comment]
Ok, so I've updated everything to typescript now. One thing I couldn't figure out is how to add types to the mocks (e.g. typescript was always complaining `property 'mockResolvedValue' does not exist on type scanFromFile` which is a legit complaint but I just ignored those warnings with `@ts-ignore`)

**Comment by victorperin** [comment]
@SimonSiefke I think we can still use test files as .js, so we simplify by now the testing process and don't need to keep ignoring them.

Also, I need to think about how is it deploying. If you want, you can help running `npm pack` and checking inside the .tar.gz file it generates.

**Comment by SimonSiefke** [comment]
I don't think its possible to import `ts` files inside `js` files. I've updated the test files so now there is only a single `@ts-nocheck` above each test file. I have had good experiences with `ts-jest` and the testing workflow is just the same as for `js` files.

Also, I have updated the files that are ignored by npm, now the src folder is ignored and only `dist` files (except for test files), `package.json` and `readme.md` will be published.

**Comment by SimonSiefke** [comment]
@victorperin Can you have another look?

**Comment by victorperin** [comment]
merged in #117

**Pull request closed without merging**
