### PR TITLE
Fix "Push to github npm registry"

### LINKED ISSUE #15: Push to github npm registry
For some reason, it's falling to push to github npm registry.

### PR DESCRIPTION
**Pull request by tsturtz**
Increment version before attempting to republish

closes #15

### CODE REVIEW

**Comment by victorperin** [comment]
Hello @tsturtz. :)

I think this is not the best way to go with it, because goes against semantic versioning.

Right now we can changing manually the version. (i intend to improve this someday)

My biggest problem is related with GitHub package registry. I never used it before, i just know they have a registry now. :P

**Comment by tsturtz** [comment]
Heya :) Sure that makes sense - it was failing at some point because it was trying to republish the same version which is why I proposed this solution.

Hm ah yes, so not actually "npm". That and actions are newish to me I'll check it out tomorrow if it hasn't been solved. Here's some good material looks like.. https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry

**Comment by victorperin** [comment]
Thank you. I should pay more attention on those issues descriptions, sorry.

I'll look over this link tomorrow, but will still wait if you want to close it.

**Comment by tsturtz** [comment]
Hi @victorperin it looks like the github actions have some other issues now, but last I saw it seemed like it was having trouble authenticating. I'll close this PR for now but if I can help in some way let me know!

**Pull request closed without merging**
